---
# SPDX-FileCopyrightText: 2021 HH Partners, Attorneys-at-law Ltd <doubleopen@hhpartners.fi>
# SPDX-License-Identifier: CC0-1.0

name: Check

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  ORT_VERSION: 9.0.0

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup ORT helper-cli
        run: |
          wget https://github.com/oss-review-toolkit/ort/releases/download/$ORT_VERSION/orth-$ORT_VERSION.zip
          unzip orth-$ORT_VERSION.zip -d /opt
      - name: Check license-classifications.yml
        run: /opt/orth-$ORT_VERSION/bin/orth list-license-categories -i license-classifications.yml

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: license-classifications.yml
